CREATE TABLE `business_settings` (
	`id` integer PRIMARY KEY NOT NULL,
	`company_name` text DEFAULT 'Pixel Hutch' NOT NULL,
	`legal_name` text DEFAULT 'Hutch & Son''s LLC' NOT NULL,
	`support_email` text DEFAULT 'max@pixel-hutch.com' NOT NULL,
	`phone` text DEFAULT '' NOT NULL,
	`website` text DEFAULT 'https://pixel-hutch.com' NOT NULL,
	`address` text DEFAULT 'Phoenix, Arizona' NOT NULL,
	`timezone` text DEFAULT 'America/Phoenix' NOT NULL,
	`currency` text DEFAULT 'USD' NOT NULL,
	`estimate_prefix` text DEFAULT 'EST' NOT NULL,
	`invoice_prefix` text DEFAULT 'INV' NOT NULL,
	`payment_terms_days` integer DEFAULT 14 NOT NULL,
	`default_tax_rate` integer DEFAULT 0 NOT NULL,
	`default_deposit_percent` integer DEFAULT 50 NOT NULL,
	`estimate_expiration_days` integer DEFAULT 30 NOT NULL,
	`task_reminder_days` integer DEFAULT 2 NOT NULL,
	`invoice_reminder_days` integer DEFAULT 3 NOT NULL,
	`notify_new_leads` integer DEFAULT true NOT NULL,
	`notify_client_messages` integer DEFAULT true NOT NULL,
	`notify_overdue_invoices` integer DEFAULT true NOT NULL,
	`client_show_progress` integer DEFAULT true NOT NULL,
	`client_show_tasks` integer DEFAULT true NOT NULL,
	`client_allow_uploads` integer DEFAULT true NOT NULL,
	`client_allow_messages` integer DEFAULT true NOT NULL,
	`accent_color` text DEFAULT '#f54702' NOT NULL,
	`updated_by` text DEFAULT 'system' NOT NULL,
	`updated_at` text NOT NULL
);
